import { Toaster } from '@/components/ui/sonner'
import '@/styles/globals.css'
import { Fragment } from 'react'

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//     icons: {
//         apple: '/apple-touch-icon.png',
//         shortcut: '/favicon.ico',
//         icon: '/favicon.ico',
//     },
// }

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <Fragment>
            {children}
            <Toaster richColors />
        </Fragment>
    )
}
