import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/provider/theme'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Admin Panel',
        description: 'Generated by IIT',
        icons: {
            apple: '/assets/apple-touch-icon.png',
            shortcut: '/assets/favicon.ico',
            icon: '/assets/favicon.ico',
        },
    }
}

export default async function RootLayout(
    props: Readonly<{
        children: React.ReactNode
    }>
) {
    return (
        <html lang='vi' suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className='bg-background text-foreground'>{props.children}</div>
                </ThemeProvider>
            </body>
        </html>
    )
}
